/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lduboeuf.gestform.ui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.lduboeuf.gestform.model.Formation;
import org.lduboeuf.gestform.model.dao.FormationDAO;
import org.lduboeuf.gestform.model.dao.StagiaireDAO;

/**
 *
 * @author lionel
 */
public class Main extends javax.swing.JFrame {

    FormationTableModel tblFormationModel;
    StagiairesTableModel listStagiairesModel;
    /**
     * Creates new form Main
     */
    public Main() {
        
        tblFormationModel = new FormationTableModel(FormationDAO.findAll());
        listStagiairesModel = new StagiairesTableModel(new ArrayList<>()); //pas de stagiaires par défaut
        
        initComponents();
        
        tblFormations.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                
                Formation f = tblFormationModel.getFormation(tblFormations.getSelectedRow());
                
                DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
                txtCode.setText(f.getCode());
                txtNom.setText(f.getNom());
                txtDateDeb.setText(df.format(f.getDateDebut()));
                txtDateFin.setText(df.format(f.getDateFin()));
                
                listStagiairesModel.setModel(StagiaireDAO.findAll(f));
                listStagiairesModel.fireTableDataChanged();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionsContainer = new javax.swing.JPanel();
        btnAjoutStagiaire = new javax.swing.JButton();
        formationListContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFormations = new javax.swing.JTable();
        formationDetailsContainer = new javax.swing.JPanel();
        formDetailsFields = new javax.swing.JPanel();
        lblCode = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblDateDeb = new javax.swing.JLabel();
        txtDateDeb = new javax.swing.JTextField();
        lblDateFin = new javax.swing.JLabel();
        txtDateFin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        formDetailsActions = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListeStagiaires = new javax.swing.JTable();
        formationListHeadContainer = new javax.swing.JPanel();
        lblListFormation = new javax.swing.JLabel();
        btnAjoutFormation = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuFileFermer = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GestForm");
        setPreferredSize(new java.awt.Dimension(1024, 800));

        actionsContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAjoutStagiaire.setText("Ajouter un stagiaire");
        actionsContainer.add(btnAjoutStagiaire);

        getContentPane().add(actionsContainer, java.awt.BorderLayout.SOUTH);

        formationListContainer.setName(""); // NOI18N
        formationListContainer.setLayout(new javax.swing.BoxLayout(formationListContainer, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setPreferredSize(null);

        tblFormations.setModel(tblFormationModel);
        tblFormations.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblFormations);

        formationListContainer.add(jScrollPane1);

        getContentPane().add(formationListContainer, java.awt.BorderLayout.WEST);

        formationDetailsContainer.setLayout(new javax.swing.BoxLayout(formationDetailsContainer, javax.swing.BoxLayout.Y_AXIS));

        formDetailsFields.setLayout(new java.awt.GridLayout(5, 2));

        lblCode.setText("code:");
        formDetailsFields.add(lblCode);

        txtCode.setEditable(false);
        txtCode.setToolTipText("");
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        formDetailsFields.add(txtCode);

        lblNom.setText("nom:");
        formDetailsFields.add(lblNom);

        txtNom.setEditable(false);
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        formDetailsFields.add(txtNom);

        lblDateDeb.setText("date début:");
        formDetailsFields.add(lblDateDeb);

        txtDateDeb.setEditable(false);
        formDetailsFields.add(txtDateDeb);

        lblDateFin.setText("date fin:");
        formDetailsFields.add(lblDateFin);

        txtDateFin.setEditable(false);
        txtDateFin.setToolTipText("");
        formDetailsFields.add(txtDateFin);

        jLabel1.setText("Liste des stagiaires:");
        formDetailsFields.add(jLabel1);

        formationDetailsContainer.add(formDetailsFields);

        tblListeStagiaires.setModel(listStagiairesModel);
        tblListeStagiaires.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblListeStagiaires);

        formDetailsActions.add(jScrollPane2);

        formationDetailsContainer.add(formDetailsActions);

        getContentPane().add(formationDetailsContainer, java.awt.BorderLayout.CENTER);

        formationListHeadContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblListFormation.setText("Liste des formations:");
        formationListHeadContainer.add(lblListFormation);

        btnAjoutFormation.setText("Créer une formation");
        formationListHeadContainer.add(btnAjoutFormation);

        getContentPane().add(formationListHeadContainer, java.awt.BorderLayout.PAGE_START);

        menuFile.setText("Fichier");
        menuFile.setName("FermerItem"); // NOI18N

        menuFileFermer.setText("Fermer");
        menuFileFermer.setToolTipText("");
        menuFileFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileFermerActionPerformed(evt);
            }
        });
        menuFile.add(menuFileFermer);

        menu.add(menuFile);

        jMenu3.setText("?");

        MenuItemAbout.setText("A propos");
        MenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAboutActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemAbout);

        menu.add(jMenu3);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileFermerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuFileFermerActionPerformed

    private void MenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAboutActionPerformed
        About aboutDialog = new About(this, true);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_MenuItemAboutActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemAbout;
    private javax.swing.JPanel actionsContainer;
    private javax.swing.JButton btnAjoutFormation;
    private javax.swing.JButton btnAjoutStagiaire;
    private javax.swing.JPanel formDetailsActions;
    private javax.swing.JPanel formDetailsFields;
    private javax.swing.JPanel formationDetailsContainer;
    private javax.swing.JPanel formationListContainer;
    private javax.swing.JPanel formationListHeadContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDateDeb;
    private javax.swing.JLabel lblDateFin;
    private javax.swing.JLabel lblListFormation;
    private javax.swing.JLabel lblNom;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuFileFermer;
    private javax.swing.JTable tblFormations;
    private javax.swing.JTable tblListeStagiaires;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDateDeb;
    private javax.swing.JTextField txtDateFin;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
