/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lduboeuf.gestform.ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.lduboeuf.gestform.model.Formation;
import org.lduboeuf.gestform.model.Stagiaire;
import org.lduboeuf.gestform.model.dao.StagiaireDAO;

/**
 *
 * @author lionel
 */
public class StagiaireForm extends javax.swing.JDialog {

    private Formation currentFormation;
    private StagiaireFormEventListener listener;
    /**
     * Creates new form StagiaireForm
     */
    public StagiaireForm(java.awt.Frame parent, boolean modal, Formation formation, StagiaireFormEventListener listener ) {
        super(parent, modal);
        initComponents();
        this.listener = listener;
        this.currentFormation = formation;
    }
    
    public interface StagiaireFormEventListener{
        public void onNewStagiaire(Stagiaire s);
        public void onUpdatedStagiaire(Stagiaire s);
    }

    
    private void createStagiaire(){
        
        //ici les controles sur le formulaire
        
        String matricule = txtMatricule.getText();
        String nom = txtNom.getText();
        String prenom = txtPrenom.getText();
        Stagiaire stag = new Stagiaire(nom, prenom, matricule, currentFormation);
        
        try {
            StagiaireDAO.save(stag);
            
            //ok on affiche un message que tout c'est bien passé:
            JOptionPane.showMessageDialog(null, "Le stagiaire " + nom + " a bien été créé et ajouté à la formation + " + currentFormation.getNom(), "creation stagiaire", JOptionPane.INFORMATION_MESSAGE); 
            listener.onNewStagiaire(stag);
            this.dispose();
            
        } catch (Exception ex) {
            Logger.getLogger(StagiaireForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formStagiaireFields = new javax.swing.JPanel();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblPrenom = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        lblMatricule = new javax.swing.JLabel();
        txtMatricule = new javax.swing.JTextField();
        formStagiaireActions = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("nouveau stagiaire");
        setAlwaysOnTop(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        formStagiaireFields.setLayout(new java.awt.GridLayout(3, 2));

        lblNom.setText("nom:");
        lblNom.setToolTipText("");
        formStagiaireFields.add(lblNom);
        formStagiaireFields.add(txtNom);

        lblPrenom.setText("prenom:");
        lblPrenom.setToolTipText("");
        formStagiaireFields.add(lblPrenom);
        formStagiaireFields.add(txtPrenom);

        lblMatricule.setText("matricule:");
        formStagiaireFields.add(lblMatricule);
        formStagiaireFields.add(txtMatricule);

        getContentPane().add(formStagiaireFields, java.awt.BorderLayout.NORTH);

        btnOK.setText("ok");
        btnOK.setToolTipText("");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        formStagiaireActions.add(btnOK);

        btnCancel.setText("annuler");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        formStagiaireActions.add(btnCancel);

        getContentPane().add(formStagiaireActions, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
            createStagiaire();        // TODO add your handling code here:
            
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel formStagiaireActions;
    private javax.swing.JPanel formStagiaireFields;
    private javax.swing.JLabel lblMatricule;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JTextField txtMatricule;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables
}
